# Generated by Django 4.1.7 on 2023-03-05 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrieNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children', models.JSONField(default=dict)),
                ('words', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Trie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_scrambler_app.trienode')),
            ],
        ),
    ]
